function disp_prest(tfd,t,f,x,famp,clim,fnts)
% DISP_PREST -- Display different presentations (TFD) for chirplet analysis
%
% Syntax:
%       disp_prest(tfd,t,f,x,famp,clim,fnts)
%
% Inputs:
%       tfd     image of time-frequency distribution
%       t       image time data
%       f       image frequency data
%       x       vector of the signal
%       famp    vector of amplitudes of fft
%       clim    range for axes property CLIM
%       fnts    font size of axis labels (optional)

% Author(s):    R.J. Cui
% Address:  Sensory communication lab
%           IBBME, U of Toronto
%           4 Taddle Creek Road
%           Toronto, ON M5S 3G9
%           Canada
% Email:    richard.cui@utoronto.ca

% Auto-generated by MATLAB on 26-Feb-2005 14:44:04
% (C)2005 Richard J. Cui; Created 26-Feb-2005
% $Revision: 0.7 $  $Date: 19-Mar-2005 19:25:41$

%% Parameter settings
% waveform
L = length(x);              % signal length
tlb = t(1); tub = t(2);     % time range bounds
time = linspace(tlb,tub,L);
xmax = max(abs(x));         % for plotting signal 
slb = -xmax; sub = xmax;

% spectrum
M = length(famp);           % size of the tfd frequency
flb = f(1); fub = f(2);     % frequency bounds
f_range = linspace(flb,fub,M);
ampmin = 0;
ampmax = max(abs(famp));     % famp should be positive

%% Create figure of tdf
fig_prest = figure;

%% Create axes of tdf
Axestfd = axes(...
    'CLim',clim,...
    'Layer','top',...
    'Position',[0.2821 0.3028 0.6229 0.6695],...
    'Parent',fig_prest);
set(Axestfd,'box','on','XTickLabel','','YTickLabel','');
axis(Axestfd,[tlb tub flb fub]);
hold(Axestfd,'all');

%% Create image of tdf
image(...
    'CData',tfd,...
    'CDataMapping','scaled',...
    'XData',t,...
    'YData',f,...
    'Parent',Axestfd);

%% Create axes of signal
AxesSig = axes('Position',[0.2804 0.1116 0.6264 0.1508],'Parent',fig_prest);
set(AxesSig,'box','on');
axis(AxesSig,[tlb tub slb sub]);
xlabel(AxesSig,'Time (s)','FontSize',fnts);
hold(AxesSig,'all');

%% Create plot of signal
plot(...
    time,x,...
    'Parent',AxesSig,...
    'DisplayName','sigxn',...
    'XDataSource','time',...
    'YDataSource','sigxn');

%% Create axes of spectrum
AxesFreq = axes('Position',[0.1200 0.3048 0.1308 0.6675],'Parent',fig_prest);
set(AxesFreq,'box','on');
axis(AxesFreq,[ampmin ampmax f_range(1) f_range(end)])
ylabel(AxesFreq,'Frequency (Hz)','FontSize',fnts);
hold(AxesFreq,'all');

%% Create plot of spectrum
plot(...
    famp,f_range,...
    'Color',[1 0 0],...
    'Parent',AxesFreq,...
    'DisplayName','freq');
set(gca,'XDir','reverse');

end